DT_FMT = "%Y-%m-%d %H:%M:%S"
PROJECT_KEY_LENGTH = 3
ASSIGNEE_PROBABILITY = 0.9
COMMENT_PROBABILITY = 0.5
DESCRIPTION_PROBABILITY = 0.3
LINK_PROBABILITY = 0.2
NORMAL_PRIORITY_PROBABILITY = 0.5

# Vars below are set from CLI args
DEBUG_MODE = None
IS_CSV_IMPORT = None
IS_JMETER = None
